GET  http://localhost:3333/alunos

###
POST http://localhost:3333/alunos
Content-Type: application/json

{
    "name": "Maria",
    "email": "maria@upf.br",
    "age": 25
}

###
PUT http://localhost:3333/alunos/.....
Content-Type: application/json

{
    "name": "Maria",
    "email": "maria@upf.br",
    "age": 20
}

###
DELETE http://localhost:3333/alunos/d6ecee07-c4ac-4031-81bf-7589e575f1d2
